name: TavernItemsExtended
version: '${project.version}'
main: edolce.tavernitemsextended.TavernItemsExtended
api-version: 1.19
depend: [AdvancedEnchantments]
commands:
  enchantOrb:
    description: give the enchantOrb
    usage: /enchantOrb